# Build the container
# docker build --tag wenkokke/musllinux_1_1_ghc945_x86_64 --file dockerfiles/Dockerfile.musllinux_1_1_ghc945_x86_64 .
FROM quay.io/pypa/musllinux_1_1_x86_64

# Install prerequisites
RUN apk add gmp-dev

# Install GHC and Cabal
RUN <<EOT bash
set -ex

# Install wget 3.2
python3.11 -m pip install wget==3.2

# Install GHC 9.2.6
python3.11 -c "import wget; wget.download('https://downloads.haskell.org/~ghc/9.2.6/ghc-9.2.6-x86_64-alpine3.12-linux-gmp.tar.xz', '/tmp/ghc-9.2.6.tar.xz')"
python3.11 -c "import shutil; shutil.unpack_archive('/tmp/ghc-9.2.6.tar.xz', '/tmp')"
mv "/tmp/ghc-9.2.6-x86_64-unknown-linux" "/tmp/ghc-9.2.6"
(cd "/tmp/ghc-9.2.6" && ./configure --prefix="/tmp/ghc-toolset-9.2.6/root/usr")
(cd "/tmp/ghc-9.2.6" && make install)
rm -rf "/tmp/ghc-9.2.6" "/tmp/ghc-9.2.6.tar.xz"

# Bootstrap Cabal 3.10.1.0
python3.11 -c "import wget; wget.download('https://github.com/haskell/cabal/archive/refs/tags/cabal-install-v3.10.1.0.zip', '/tmp/cabal.zip')"
python3.11 -c "import shutil; shutil.unpack_archive('/tmp/cabal.zip', '/tmp')"
mv "/tmp/cabal-cabal-install-v3.10.1.0" "/tmp/cabal"
(cd "/tmp/cabal" && python3 "./bootstrap/bootstrap.py" -d "./bootstrap/linux-9.2.6.json" -w "/tmp/ghc-toolset-9.2.6/root/usr/bin/ghc-9.2.6")
PATH="/tmp/ghc-toolset-9.2.6/root/usr/bin:${PATH}" "/tmp/cabal/_build/bin/cabal" v2-update
PATH="/tmp/ghc-toolset-9.2.6/root/usr/bin:${PATH}" "/tmp/cabal/_build/bin/cabal" v2-install cabal-install cabal-install --overwrite-policy=always --install-method=copy --installdir="/tmp/ghc-toolset-9.2.6/root/usr/bin"

# Bootstrap GHC 9.4.5
python3.11 -c "import wget; wget.download('https://downloads.haskell.org/~ghc/9.4.5/ghc-9.4.5-src.tar.xz', '/tmp/ghc-9.4.5-src.tar.xz')"
python3.11 -c "import shutil; shutil.unpack_archive('/tmp/ghc-9.4.5-src.tar.xz', '/tmp')"

## Create and apply the fpic-default patch
mkdir "/tmp/ghc-9.4.5-patches"
cat > "/tmp/ghc-9.4.5-patches/fpic-default.patch" <<EOP
Index: ghc-9.4.5/compiler/GHC/Driver/Session.hs
===================================================================
--- ghc-9.4.5.orig/compiler/GHC/Driver/Session.hs
+++ ghc-9.4.5/compiler/GHC/Driver/Session.hs
@@ -3871,6 +3871,7 @@ default_PIC platform =
     -- of that.  Subsequently we expect all code on aarch64/linux (and macOS) to
     -- be built with -fPIC.
     (OSDarwin,  ArchAArch64) -> [Opt_PIC]
+    (OSLinux,   ArchX86_64)  -> [Opt_PIC]
     (OSLinux,   ArchAArch64) -> [Opt_PIC, Opt_ExternalDynamicRefs]
     (OSLinux,   ArchARM {})  -> [Opt_PIC, Opt_ExternalDynamicRefs]
     (OSOpenBSD, ArchX86_64)  -> [Opt_PIC] -- Due to PIE support in
EOP
(cd "/tmp" && patch -p0 < "/tmp/ghc-9.4.5-patches/fpic-default.patch")

## Create and update mk/build.mk
cp "/tmp/ghc-9.4.5/mk/build.mk.sample" "/tmp/ghc-9.4.5/mk/build.mk"
cat >> "/tmp/ghc-9.4.5/mk/build.mk" <<EOP

GhcLibHcOpts += -fPIC
GhcRtsHcOpts += -fPIC
GhcRtsCcOpts += -fPIC
BuildFlavour = quick
EOP

## Install GHC 9.4.5
(cd "/tmp/ghc-9.4.5" && PATH="/tmp/ghc-toolset-9.2.6/root/usr/bin:${PATH}" ./configure GHC="/tmp/ghc-toolset-9.2.6/root/usr/bin/ghc-9.2.6")
(cd "/tmp/ghc-9.4.5" && PATH="/tmp/ghc-toolset-9.2.6/root/usr/bin:${PATH}" hadrian/build install --docs=none -j --prefix="/usr/local")
rm -rf "/tmp/ghc-toolset-9.2.6/root/usr" "/tmp/ghc-9.4.5" "/tmp/ghc-9.4.5-src.tar.xz"

# Install Cabal 3.10.1.0
"/tmp/cabal/_build/bin/cabal" v2-install cabal-install cabal-install --overwrite-policy=always --install-method=copy --installdir="/usr/local/bin"
rm -rf "/tmp/cabal" "/tmp/cabal.zip"
EOT
