from typing import List

def unsafe_hs_example_haskell_wheel_version() -> str: ...
def unsafe_hs_example_haskell_wheel_main() -> int: ...
def unsafe_hs_init(args: List[str]) -> None: ...
def unsafe_hs_exit() -> None: ...
