name: cibuildwheel-windows

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize

  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: "0 0 * * 0"

  workflow_dispatch:

jobs:
  test:
    name: Build wheels for ${{ matrix.os.name }} / GHC ${{ matrix.ghc.version }} / Python ${{ matrix.python.version }}
    runs-on: ${{ matrix.os.tag }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - { tag: windows-latest, name: Windows }
        ghc:
          - { version: "9.6.1" }
          - { version: "9.4.4" }
          # 01-04-2023:
          # Compilation with GHC 9.2.7 fails because `ld` cannot find the library `HSrts`.
          # See: https://github.com/wenkokke/example-haskell-wheel/issues/1
          # - { version: "9.2.7" }
        cabal:
          - { version: "3.10.1.0" }
        python:
          - { version: "3.11", tag: "311" }
          - { version: "3.10", tag: "310" }
          - { version: "3.9", tag: "39" }
          - { version: "3.8", tag: "38" }
          - { version: "3.7", tag: "37" }

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GHC ${{ matrix.ghc.version }}
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc.version }}
          cabal-version: ${{ matrix.cabal.version }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
          cache: "pip"
          cache-dependency-path: "requirements-ci.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-ci.txt
        shell: sh

      - # 01-04-2023:
        # Windows builds with cibuildwheel cannot find pythonXY.lib from the venv
        name: Build wheel
        run: |
          mkdir -p wheelhouse
          pipx run --spec build pyproject-build --wheel --outdir=wheelhouse
          pipx run delvewheel repair --wheel-dir=wheelhouse wheelhouse/*.whl
        shell: sh

      - uses: actions/upload-artifact@v3
        with:
          name: wheelhouse-GHC-${{ matrix.ghc.version }}
          path: ./wheelhouse/*.whl
